### ISSUE TITLE
Searching Unicode Symbols

### ISSUE THREAD

**Issue by lightonflux** [FineFindus/Hieroglyphic#37] opened 2024-10-11 21:38 UTC
I really like this app and would like to use the same workflow to find code points for Unicode chars, regardless of whether they have LaTeX commands.

Is this strictly out of scope for this project, or is this something that could be supported both technically and vision?

**Comment by FineFindus** [comment] 2024-10-11 22:02
Duplicate of #14.

Thanks for the suggestion, I think that it would fit much better in [Characters](https://apps.gnome.org/Characters/) since they already deal with searching for Unicode characters. 
I'm happy to help out if someone wants to create an MR for it (or fork Hieroglyphic to add it). The major technical issue would be finding a suitable dataset of hand drawn unicode character to train the model on.

**Closed** 2024-10-11 22:02 UTC
